import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header'
import HomeBanner from '../components/HomeBanner'
import Services from '../components/Services'
import OurWorks from '../components/OurWorks'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Active-IT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header/>
      <HomeBanner/>
      <Services/>
      <OurWorks/>
      <Footer/>
    </div>
  )
}

export default Home
