import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import HomeBanner from '../components/HomeBanner'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Active-IT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header/>
      <HomeBanner/>
    </div>
  )
}

export default Home
